"""build_fonts.py - inline the report's typefaces as @font-face data URIs.

An Artifact runs under a CSP that blocks font CDNs, so a linked Google Fonts
stylesheet fails silently and the page falls back to system faces - which looks
like nothing was chosen. Embedding the woff2 bytes is the only way to actually
ship a typeface.

Faces are the ones NFL Savant itself loads, read off its own <head>:
Inter Tight for UI, Big Shoulders Display for the masthead, Roboto Mono for
figures. All three are SIL Open Font License.

Only the `latin` subset is fetched. The full family with every subset is
megabytes; latin alone is ~15-25 KB a weight.

Usage:
    py -3 scripts/build_fonts.py
"""

from __future__ import annotations

import argparse
import base64
import re
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36")

# (css family name, weights) - kept deliberately short. Every extra weight is
# another 20 KB in a file that already carries 32 team crests.
# IBM PLEX, the whole superfamily. Chosen over Inter Tight / Big Shoulders
# because those read as generic product-UI: a condensed uppercase display face
# is striking once and tiring in a table, and Inter is the default everyone
# reaches for. Plex was drawn for technical and financial interfaces - it holds
# up at 11px, its figures are unambiguous (slashed zero, distinct 1/l/I), and
# Sans, Mono and Serif share one skeleton so the page reads as one voice
# instead of three borrowed ones.
# Five faces, not eight. Each is ~45 KB for Sans and the page has a hard
# payload ceiling; 500 and 700 were doing work that 400 and 600 already do.
WANT = [
    ("IBM Plex Sans", [400, 600]),
    ("IBM Plex Sans Condensed", [400, 600, 700]),
    ("IBM Plex Mono", [400, 600]),
    ("IBM Plex Serif", [600]),
]


def fetch(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=45) as r:
        return r.read()


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("-o", "--out", default="scripts/font_assets.py")
    a = ap.parse_args()

    faces, total = [], 0
    for fam, weights in WANT:
        q = fam.replace(" ", "+") + ":wght@" + ";".join(str(w) for w in weights)
        css = fetch(f"https://fonts.googleapis.com/css2?family={q}&display=swap"
                    ).decode("utf-8")
        # The API returns one @font-face block per subset; keep latin only.
        blocks = re.findall(r"/\*\s*([\w-]+)\s*\*/\s*@font-face\s*\{(.*?)\}",
                            css, re.S)
        for subset, body in blocks:
            if subset != "latin":
                continue
            w = re.search(r"font-weight:\s*(\d+)", body)
            u = re.search(r"url\((https://[^)]+\.woff2)\)", body)
            if not (w and u):
                continue
            raw = fetch(u.group(1))
            total += len(raw)
            faces.append((fam, int(w.group(1)),
                          base64.b64encode(raw).decode()))
            print(f"  {fam} {w.group(1)} - {len(raw)/1024:.0f} KB")

    css_out = "".join(
        f"@font-face{{font-family:'{fam}';font-style:normal;font-weight:{w};"
        f"font-display:swap;src:url(data:font/woff2;base64,{b64}) "
        f"format('woff2')}}" for fam, w, b64 in faces)

    Path(a.out).write_text(
        '"""Auto-generated by build_fonts.py. Embedded @font-face rules."""\n\n'
        "FONT_CSS = " + repr(css_out) + "\n", encoding="utf-8")
    print(f"  {len(faces)} faces, {total/1024:.0f} KB raw -> "
          f"{len(css_out)/1024:.0f} KB inlined")
    print(f"  wrote {a.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
